apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-distancia
  labels:
    app: conversao-distancia
  annotations:
    description: "Deployment para o serviço de conversão de distância"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversao-distancia
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: conversao-distancia
    spec:
      containers:
        - name: conversao-distancia
          image: alexsessa/conversao-distancia:v2
          ports:
          - containerPort: 5000
          resources:
            limits:
              memory: "4Gi"
              cpu: "4"
            requests:
              memory: "2Gi"
              cpu: "2"
          env:
            - name: ENVIRONMENT
              value: "production"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5
      volumes:
        - name: config-volume
          configMap:
            name: conversao-distancia-config

---

apiVersion: v1
kind: Service
metadata:
  name: conversao-distancia
  labels:
    app: conversao-distancia
spec:
  selector:
    app: conversao-distancia
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort